#pragma once

#include "driver/gpio.h"

/* GPIO13 is not an ESP32 boot-strapping pin and is reserved for the stop input. */
#define ROBOT_EMERGENCY_GPIO GPIO_NUM_13
#define ROBOT_MOTOR_LEFT_FORWARD GPIO_NUM_25
#define ROBOT_MOTOR_LEFT_REVERSE GPIO_NUM_26
#define ROBOT_MOTOR_RIGHT_FORWARD GPIO_NUM_27
#define ROBOT_MOTOR_RIGHT_REVERSE GPIO_NUM_14

#define ROBOT_MOTOR_PWM_LEFT GPIO_NUM_33
#define ROBOT_MOTOR_PWM_RIGHT GPIO_NUM_32

#define ROBOT_LED_STRIP_GPIO GPIO_NUM_4
#define ROBOT_AUDIO_I2S_LRCK GPIO_NUM_22
#define ROBOT_AUDIO_I2S_BCLK GPIO_NUM_23
#define ROBOT_AUDIO_I2S_DOUT GPIO_NUM_21
#define ROBOT_AUDIO_SAMPLE_RATE 16000
#ifndef CONFIG_ROBOT_AUDIO_DMA_BUF_LEN
#define CONFIG_ROBOT_AUDIO_DMA_BUF_LEN 256
#endif
#ifndef CONFIG_ROBOT_AUDIO_SELF_MONITOR
#define CONFIG_ROBOT_AUDIO_SELF_MONITOR 0
#endif
#define ROBOT_AUDIO_DMA_BUF_LEN CONFIG_ROBOT_AUDIO_DMA_BUF_LEN
#define ROBOT_AUDIO_SELF_MONITOR CONFIG_ROBOT_AUDIO_SELF_MONITOR

#define ROBOT_ADC_BATTERY GPIO_NUM_34
#define ROBOT_ADC_LIGHT GPIO_NUM_35

#define ROBOT_WATCHDOG_TIMEOUT_MS 5000
